import type { TailorResult } from "@/lib/schemas/tailor";

function escapeLatex(value: string): string {
  return value
    .replace(/\\/g, "\\textbackslash{}")
    .replace(/&/g, "\\&")
    .replace(/%/g, "\\%")
    .replace(/\$/g, "\\$")
    .replace(/#/g, "\\#")
    .replace(/_/g, "\\_")
    .replace(/\{/g, "\\{")
    .replace(/\}/g, "\\}")
    .replace(/~/g, "\\textasciitilde{}")
    .replace(/\^/g, "\\textasciicircum{}");
}

export function generateTailoredResumeLatex(
  result: TailorResult,
  targetJd: string
): string {
  const skills = result.matchedSkills
    .map((skill) => escapeLatex(skill))
    .join(" / ");

  const projects = result.selectedProjects
    .map((project) => {
      const bullets = project.tailoredBullets
        .map((bullet) => `    \\item ${escapeLatex(bullet)}`)
        .join("\n");

      return [
        `\\subsection*{${escapeLatex(project.projectName)} \\hfill ${escapeLatex(project.role)}}`,
        "\\begin{itemize}",
        bullets,
        "\\end{itemize}",
      ].join("\n");
    })
    .join("\n\n");

  const highFrequencyQuestions = result.interviewPreparation.highFrequencyQuestions
    .map((question) => `    \\item ${escapeLatex(question)}`)
    .join("\n");

  const weaknessQuestions = result.interviewPreparation.weaknessQuestions
    .map((question) => `    \\item ${escapeLatex(question)}`)
    .join("\n");

  return [
    "\\documentclass[11pt,a4paper]{ctexart}",
    "\\usepackage[margin=1in]{geometry}",
    "\\usepackage[hidelinks]{hyperref}",
    "\\usepackage{enumitem}",
    "\\usepackage{xcolor}",
    "\\setlist[itemize]{leftmargin=1.5em,itemsep=0.35em,topsep=0.35em}",
    "\\pagestyle{empty}",
    "",
    "\\begin{document}",
    "",
    "\\begin{center}",
    "{\\LARGE \\textbf{Tailored Resume Draft}}\\\\[0.35em]",
    "{\\small Generated by Resume Copilot}",
    "\\end{center}",
    "",
    "\\section*{个人优势总结}",
    escapeLatex(result.tailoredSummary),
    "",
    "\\section*{匹配技能}",
    skills || "暂无",
    "",
    "\\section*{精选项目经历}",
    projects || "暂无项目内容。",
    "",
    "\\section*{面试准备}",
    "\\subsection*{高频问题}",
    "\\begin{itemize}",
    highFrequencyQuestions,
    "\\end{itemize}",
    "",
    "\\subsection*{压力测试题}",
    "\\begin{itemize}",
    weaknessQuestions,
    "\\end{itemize}",
    "",
    "\\subsection*{面试策略建议}",
    escapeLatex(result.interviewPreparation.tips),
    "",
    "\\section*{目标岗位 JD 备忘}",
    escapeLatex(targetJd),
    "",
    "\\end{document}",
    "",
  ].join("\n");
}
